#!/bin/sh
#
# Contain Environment variables for installs
#

HOME_DIR="/home/vagrant"

SHARED_DIR="/vagrant"

DOWNLOAD_DIR="$SHARED_DIR/downloads"
if [ ! -d $DOWNLOAD_DIR ]; then
  mkdir $DOWNLOAD_DIR
fi

FUSEKI_VERSION=2.3.0
FUSEKI_BASE=/etc/fuseki
FUSEKI_DEPLOY=/var/lib/tomcat7/webapps

SOLR_VERSION=4.10.3
SOLR_HOME=/var/lib/tomcat7/solr

KARAF_VERSION=4.0.1
